const UI_TRANSLATIONS = new Map(Object.entries({
  "오늘의 학습": "Today's Learning",
  "오늘의 단어": "Today's Vocabulary",
  "오늘의 표현 하나 익히기": "Learn Today's Expression",
  "오늘의 TED 학습": "Today's TED Learning",
  "오늘의 TED 메시지 이해하기": "Understand Today's TED Message",
  "오늘의 수능 지문": "Today's CSAT Passage",
  "유형별 훈련": "Question Type Training",
  "어휘 / 구문": "Vocabulary / Syntax",
  "부모 점검": "Parent Dashboard",
  "출처 정책": "Source Policy",
  "표현 업그레이드": "Expression Upgrade",
  "유의어 공부": "Synonym Study",
  "유의어 학습": "Synonym Study",
  "단어장": "Vocabulary",
  "매일 1문장": "Daily Sentence",
  "영어 뉴스": "English News",
  "TED 학습": "TED Learning",
  "매일 토익 풀기": "Daily TOEIC",
  "나만의 학습장": "My Study Room",
  "학습 캘린더": "Study Calendar",
  "최애 블로그": "Favorite Blogs",
  "설정": "Settings",
  "설정 열기": "Open settings",
  "설정 닫기": "Close settings",
  "학습 트랙 선택": "Select learning track",
  "일반": "General",
  "수능": "CSAT",
  "초등": "Elementary",
  "중등": "Middle School",
  "일반 모드 학습자": "General learner",
  "수능 모드 학습자": "CSAT learner",
  "12일 연속 학습 중!": "12-day learning streak!",
  "이번 주도 멋져요": "Great work this week",
  "학습자 변경": "Change learner",
  "변경": "Change",
  "오늘 무엇을 공부할까요?": "What would you like to study today?",
  "추천 학습 링크": "Recommended learning links",
  "매일미드한문장": "Daily TV English",
  "매일 토익 RC 풀기": "Daily TOEIC RC",
  "TED 바로가기": "Go to TED",
  "오늘의 학습 체크": "Today's Learning",
  "오늘의 학습 코치": "Today's Learning Coach",
  "완료한 항목과 바로 이어갈 복습을 기준으로 다음 행동을 제안합니다.": "Your next step is based on completed items and reviews ready to continue.",
  "완료 여부와 오늘의 전체 달성률을 한눈에 확인해보세요.": "See today's completion status and overall progress at a glance.",
  "오늘의 수능 학습": "Today's CSAT Learning",
  "완료": "Complete",
  "완료됨": "Completed",
  "진행 전": "Not started",
  "학습 전": "Not started",
  "학습 대기": "Ready",
  "진행 중": "In progress",
  "아직 시작하지 않았어요": "Not started yet",
  "완료 기록 대기": "Waiting for completion",
  "오늘 주요 학습을 모두 끝냈어요.": "You completed today's main learning.",
  "오늘의 체크 초기화": "Reset today's progress",
  "다음 추천": "Recommended next",
  "복습 필요": "Review needed",
  "약점 신호": "Weakness signals",
  "기초 어휘": "Core vocabulary",
  "단어 복습하기": "Review vocabulary",
  "오늘 학습할 단어를 빠르게 확인하고 뜻과 표현을 익혀보세요.": "Quickly review today's words and learn their meanings and usage.",
  "자주 쓰는 표현을 짧게 배우고 같은 패턴으로 바로 연습해보세요.": "Learn a useful expression and immediately practice the same pattern.",
  "약 1분 · 패턴 훈련": "About 1 min · Pattern practice",
  "오늘 표현 익히기": "Learn today's expression",
  "오늘의 뉴스 표현을 통해 실제 영어 표현 감각을 키워보세요.": "Build natural English awareness through today's news expressions.",
  "실전 읽기": "Practical reading",
  "화자의 이야기 흐름 속에서 장면과 핵심 메시지를 이해해보세요.": "Understand the scene and key message within the speaker's flow.",
  "약 3분 · 맥락 이해": "About 3 min · Context practice",
  "짧은 테스트로 오늘 학습한 내용을 가볍게 점검해보세요.": "Use a short test to check what you learned today.",
  "빠른 점검": "Quick check",
  "테스트 풀기": "Take the test",
  "문제를 풀고 오답을 확인하면서 실력을 정리해보세요.": "Solve questions and review mistakes to strengthen your skills.",
  "오답 복습": "Wrong-answer review",
  "오답 점검": "Review mistakes",
  "오늘 바로 쓸 표현 1개": "1 useful expression for today",
  "복습할 표현 저장 가능": "Save an expression for review",
  "약 1분 · 대표 문장 + 빠른 체크": "About 1 min · Key sentence + quick check",
  "오늘 확인할 기사 1개": "1 article for today",
  "핵심 표현 3개 확인": "Review 3 key expressions",
  "실제 문장 감각 유지": "Build a feel for authentic sentences",
  "오늘의 TED 장면 1개": "1 TED scene for today",
  "화자 · 맥락 · 메시지 확인": "Review speaker · context · message",
  "스피치의 생각과 흐름 이해하기": "Understand the ideas and flow of the talk",
  "오늘 학습 기반 3문항": "3 questions from today's learning",
  "단어 / 문장 / 문법 복습 포함": "Includes vocabulary, sentence, and grammar review",
  "빠르게 오늘 내용 확인": "Quickly check today's material",
  "오늘 추천 문제 3개": "3 recommended questions",
  "문법 + 짧은 독해 포함": "Includes grammar + short reading",
  "최근 풀이 기록 없음": "No recent attempts",
  "점수 기록 없음": "No score yet",
  "최근 학습 기록 없음": "No recent study record",
  "저장 단어를 만들어보세요": "Save words to build your review list",
  "복습 이어하기": "Continue review",
  "완료된 학습": "Completed",
  "최근 약한 유형: Reading": "Recent weak area: Reading",
  "최근 약한 유형: 문맥 추론": "Recent weak area: Context inference",
  "문맥 추론": "Context inference",
  "아직 약점 데이터가 부족해요": "Not enough data to identify a weak area yet",
  "매일 1페이지가 새로 갱신돼요": "A new page is added every day",
  "앞으로 할 업무나 결정을 나타냄": "Expresses a future task or decision",
  "will + 동사원형": "will + base verb",
  "화자 · 맥락 · 메시지 확인": "Review the speaker, context, and message",
  "스피치의 생각과 흐름 이해하기": "Understand the speaker's ideas and flow",
  "오늘 학습 완료": "Today's study completed",
  "완료 취소": "Undo completion",
  "완료 표시": "Mark complete",
  "학습 화면으로 이동": "Open study screen",
  "오늘의 5개": "Today's 5",
  "수능형 어휘": "CSAT vocabulary",
  "문장을 넘어 화자의 생각과 흐름까지": "Beyond sentences: follow the speaker's ideas and flow",
  "사람들이 귀 기울이게 만드는 말하기 습관과 목소리의 힘을 배워봅니다.": "Explore the speaking habits and vocal choices that make people listen.",
  "문장 분석": "Sentence analysis",
  "전체 암기 진도율": "Overall Memorization Progress",
  "ALL CLEAR 단어와 나만의 학습장에서 ‘암기함’으로 표시한 단어를 합산합니다.": "This total combines ALL CLEAR words and words marked as memorized in My Study Room.",
  "이번 달 누적 단어를 바로 점검해보세요.": "Check the words accumulated this month.",
  "단어 테스트 시작": "Start Vocabulary Test",
  "단어와 예문을 각각 Clear하고 ALL CLEAR를 완성해보세요.": "Clear both the word and its example to achieve ALL CLEAR.",
  "학습 상태": "Study Status",
  "학습 팁": "Study Tip",
  "뜻만 외우기보다 예문까지 함께 읽으면 실제 사용 감각을 더 빠르게 익힐 수 있어요.": "Read the examples along with the meanings to build practical usage skills faster.",
  "오늘의 루틴": "Today's Routine",
  "단어 10개 소리 내어 읽기": "Read 10 words aloud",
  "뜻과 품사 확인하기": "Check meanings and parts of speech",
  "예문 한 번 따라 읽기": "Read each example aloud once",
  "저장한 단어": "Saved Words",
  "개를 모았어요": "words saved",
  "완료 해제": "Undo Completion",
  "10개 단어를 ALL CLEAR하면 오늘 학습이 자동 완료됩니다.": "Today's study is completed automatically when all 10 words reach ALL CLEAR.",
  "오늘 학습 확인용 퀵 테스트": "Quick Check for Today's Learning",
  "오늘 학습한 단어, 문장 표현, 문법 포인트를 가볍게 확인합니다.": "Quickly review today's vocabulary, sentence expressions, and grammar points.",
  "복습 대기 없음": "No reviews pending",
  "아직 테스트를 시작하지 않았어요": "The test has not been started yet",
  "최근 풀이 기록이 없어요": "No recent attempt",
  "잠재력, 가능한 잠재력": "potential; possible capacity",
  "성분; 부품": "component; part",
  "훈련; 규율을 행사하다; 주제; 규정; 훈련": "discipline; training; subject; rule",
  "be + 과거분사": "be + past participle",
  "업무 일정이나 결과의 원인을 설명함": "Explains the cause of a work schedule or outcome",
  "업무의 대상이나 처리 결과를 강조함": "Emphasizes the object of an action or its result",
  "정보의 출처나 근거를 제시함": "Presents the source or basis of information",
  "문법 포인트": "Grammar Point",
  "동사원형만": "Base verb only",
  "과거분사만": "Past participle only",
  "동명사 또는 명사": "Gerund or noun",
  "오늘 테스트 채점하기": "Grade Today's Test",
  "RC 문제": "RC Questions",
  "오늘의 한 문장": "Today's Sentence",
  "오답노트": "Wrong Answer Notes",
  "날짜별 이력": "History by Date",
  "공지문을 읽고 답하세요.": "Read the passage and answer the question.",
  "답안 선택": "Select an Answer",
  "오늘 확인 현황": "Today's Check Status",
  "기록 대기": "Awaiting results",
  "RC 확인": "RC Check",
  "단어 복습": "Vocabulary Review",
  "문장 표현": "Sentence Expressions",
  "오늘 기록 초기화": "Reset Today's Record",
  "아직 오늘 풀이 기록이 없습니다.": "There is no attempt recorded for today yet.",
  "Daily Test 안내": "About Daily Test",
  "20문제 은행을 날짜별 새 순서로 점검": "Review a 20-question bank in a new daily order",
  "단어 테스트": "Vocabulary Test",
  "오늘의 단어 10개에서 출제": "Questions drawn from today's 10 vocabulary words",
  "문장 학습": "Sentence Practice",
  "오늘의 한 문장으로 의미·패턴·활용 점검": "Review the meaning, pattern, and usage of today's sentence",
  "같은 날에는 문제와 순서가 유지되고, 날짜가 바뀌면 새로운 세트가 준비됩니다.": "Questions and order stay the same during the day; a new set is prepared the next day.",
  "화자": "Speaker",
  "오늘의 관점": "Today's Focus",
  "화자는 이 생각을 왜 강조할까요?": "Why does the speaker emphasize this idea?",
  "학습 흐름": "Learning Flow",
  "영상 → 장면 맥락 → 메시지 이해": "Video → Scene Context → Message",
  "장면을 따라가는 스크립트": "Follow-Along Transcript",
  "문장을 선택해 앞뒤 흐름을 확인하세요.": "Select a sentence to explore the surrounding context.",
  "영상과 스크립트를 함께 살펴보세요.": "Explore the video and transcript together.",
  "사용자가 제공한 전체 스크립트를 문장 단위로 표시합니다.": "The complete provided transcript is displayed sentence by sentence.",
  "오늘의 스피치 흐름": "Today's Speech Flow",
  "발표 흐름": "Talk Structure",
  "도입 · 문제 제기": "Opening · Introducing the Issue",
  "장면 맥락": "Scene Context",
  "오늘의 질문": "Today's Question",
  "오늘의 장면 이해": "Understand Today's Scene",
  "학습 중": "In progress",
  "1. 영상에서 말의 분위기와 강조를 확인하세요.": "1. Notice the speaker's tone and emphasis in the video.",
  "2. 앞뒤 스크립트와 연결해 의미를 파악하세요.": "2. Connect it with the surrounding transcript to understand the meaning.",
  "3. 화자가 전달하려는 메시지를 한 줄로 정리하세요.": "3. Summarize the speaker's message in one sentence.",
  "영상과 앞뒤 흐름을 살펴본 뒤 장면 이해를 완료해 주세요.": "Review the video and surrounding context, then mark the scene as understood.",
  "메시지를 이해하는 표현": "Expressions That Support the Message",
  "핵심 3개": "3 Key Expressions",
  "It's the most + 형용사 + 명사": "It's the most + adjective + noun",
  "가장 ~한 …이다": "It is the most ...",
  "the only one that + 동사": "the only one that + verb",
  "~하는 유일한 것/사람": "the only thing/person that ...",
  "have the experience that + 문장": "have the experience that + clause",
  "~하는 경험을 하다": "to have the experience of ...",
  "개별 표현을 외우기보다 화자가 이 표현으로 어떤 생각을 전달하는지 먼저 확인하세요.": "Focus first on the idea the speaker conveys rather than memorizing expressions in isolation.",
  "화자가 이 강연에서 전달하려는 핵심은 무엇인가요?": "What is the speaker's central message in this talk?",
  "맥락 이해 1문제": "1 Context Question",
  "미루는 습관이 어떻게 작동하는지 유쾌한 비유를 통해 이해해 봅니다.": "Understand how procrastination works through a humorous analogy.",
  "더 잘 듣고, 더 간결하게 말하며, 진짜 대화를 이어가는 방법을 익힙니다.": "Learn to listen better, speak more concisely, and sustain genuine conversations.",
  "답을 선택한 뒤 강연 전체의 메시지를 기준으로 확인하세요.": "Choose an answer, then check it against the talk's overall message.",
  "TODAY'S EXPRESSION · 약 3분": "TODAY'S EXPRESSION · About 3 min",
  "오늘 바로 쓸 수 있는 표현 하나를 대표 문장과 변형 문장으로 연습해 보세요.": "Practice one useful expression through a key sentence and variations.",
  "1 표현 확인": "1 Review expression",
  "2 패턴 반복": "2 Repeat pattern",
  "3 빠른 체크": "3 Quick check",
  "대표 문장": "Key Sentence",
  "일정·제출": "Schedule · Submission",
  "먼저 뜻을 떠올린 뒤 확인하세요": "Recall the meaning before revealing it",
  "표현 포인트": "Expression Point",
  "같은 패턴으로 말해 보세요": "Practice with the same pattern",
  "1개 문장": "1 sentence",
  "변형 1": "Variation 1",
  "운영팀은 교육 자료를 월례 회의 전에 제출할 예정입니다.": "The operations team will submit the training materials before the monthly meeting.",
  "오늘 표현의 의미는 무엇인가요?": "What does today's expression mean?",
  "정중하게 업무를 요청함": "Politely requests an action",
  "현재와 관련된 완료 상태를 나타냄": "Describes a completed state connected to the present",
  "답을 선택한 뒤 정답을 확인하세요.": "Choose an answer, then check the correct answer.",
  "빠른 체크 후 오늘 학습을 마무리하세요.": "Finish today's lesson after the quick check.",
  "will + 동사원형 패턴을 대표 문장과 변형 문장으로 연습했습니다.": "You practiced the will + base verb pattern with a key sentence and variations.",
  "저장한 표현": "Saved Expressions",
  "저장 버튼으로 다시 연습할 표현을 모아보세요.": "Use Save to collect expressions for further practice.",
  "오늘의 학습 가이드": "Today's Learning Guide",
  "표현을 확인하고 같은 패턴을 반복한 뒤 빠른 체크로 마무리하세요.": "Review the expression, repeat the pattern, and finish with a quick check.",
  "welcoming · 편안한, 반기는": "welcoming · friendly and inviting",
  "designed · ~하도록 설계된": "designed · made for a specific purpose",
  "해석": "Translation",
  "단어 저장": "Save Word",
  "하이라이트": "Highlight",
  "영어 문제풀이": "English Practice Questions",
  "Part 5·6과 Part 7 중 오늘 풀 유형을 선택하세요.": "Choose Part 5·6 or Part 7 for today's practice.",
  "다크모드": "Dark Mode",
  "문법·어휘·문장 흐름을 빠르게 점검하는 객관식 문제": "Multiple-choice questions for a quick grammar, vocabulary, and sentence-flow check",
  "문법·어휘·문장 완성": "Grammar · Vocabulary · Sentence Completion",
  "Part 5와 Part 6 통합 학습": "Combined Part 5 and Part 6 practice",
  "최근 7일 풀이와 겹치지 않음": "No repeats from the last 7 days",
  "오늘의 새 문제": "New Questions Today",
  "문항": "Questions",
  "이메일·공지문·안내문·기사형 지문을 읽는 독해 문제": "Reading questions based on emails, notices, guides, and articles",
  "지문 기반 4지선다": "Passage-based multiple choice",
  "핵심 정보와 목적 파악": "Identify key information and purpose",
  "최근 풀이 지문 제외": "Excludes recently attempted passages",
  "오늘의 새 독해": "New Reading Today",
  "지문·문항": "Passages · Questions",
  "오답·북마크 복습": "Review Wrong Answers · Bookmarks",
  "신규 문제와 섞지 않고, 다시 확인할 문제만 모아서 풀어보세요.": "Practice only the questions that need review, separately from new questions.",
  "완전히 지친 하루": "An Exhausting Day",
  "VERY 없이 강한 상태를 한 단어로 표현해요.": "Express a strong state with one word instead of VERY.",
  "약 4분": "About 4 min",
  "난이도 1": "Level 1",
  "오늘 바꿔볼 표현": "Expressions to Upgrade Today",
  "저장하고, 복습하고, 실제로 사용해보세요.": "Save, review, and use what you learn.",
  "단어·문장·스크랩 표현을 테스트와 비즈니스 이메일 쓰기로 연결합니다.": "Connect saved words, sentences, and clips to tests and business email writing.",
  "저장 단어": "Saved Words",
  "저장 표현": "Saved Expressions",
  "아직 저장한 단어가 없어요.": "No saved words yet.",
  "단어장 우측 상단 북마크를 눌러 복습할 단어를 모아보세요.": "Use the bookmark on vocabulary cards to collect words for review.",
  "단어 저장하러 가기": "Save Vocabulary",
  "저장한 문장": "Saved Sentences",
  "아직 저장한 문장이 없어요.": "No saved sentences yet.",
  "매일 1문장에서 북마크를 눌러 다시 읽을 문장을 모아보세요.": "Use bookmarks in Daily Sentence to collect sentences for review.",
  "문장 저장하러 가기": "Save Sentences",
  "완료 단위 기록": "Completed Learning Units",
  "이번 달 학습한 날": "Study Days This Month",
  "누적 완료 단위": "Total Completed Units",
  "복습 저장 항목": "Saved Review Items",
  "아직 완료한 학습 단위가 없습니다.": "No completed learning units yet.",
  "단어": "Vocabulary",
  "단어 10개 완료": "10 vocabulary words completed",
  "문장": "Sentence",
  "문장 1개 학습": "1 sentence studied",
  "미드 숏폼": "TV Shorts",
  "미드 대사 카드 3개": "3 TV dialogue cards",
  "뉴스": "News",
  "기사 1편 읽기": "1 article read",
  "완료한 학습 단위": "Completed Learning Units",
  "단": "V",
  "문": "S",
  "미": "TV",
  "뉴": "N",
  "일": "Sun",
  "월": "Mon",
  "화": "Tue",
  "수": "Wed",
  "목": "Thu",
  "금": "Fri",
  "토": "Sat",
  "최애 블로그에서 새로운 영어 표현을 확인해보세요.": "Discover new English expressions from your favorite blogs.",
  "그 말이 일리가 있네요.": "That makes sense.",
  "상대방의 의견을 이해했다는 신호를 자연스럽게 전달합니다.": "Naturally show that you understand the other person's point.",
  "자주 참고하는 영어 학습 블로그": "Frequently Used English Learning Blogs",
  "이름을 누르면 해당 블로그가 새 탭에서 열립니다.": "Select a name to open the blog in a new tab.",
  "유의어·어휘 확장 참고 순서": "Reference Order for Synonyms and Vocabulary Expansion",
  "ValueTime 기존 단어·표현 콘텐츠": "Existing ValueTime Vocabulary and Expression Content",
  "정답·뜻·예문·수능 적합성의 최우선 기준": "Primary standard for answers, meanings, examples, and CSAT suitability",
  "유의어 후보, 강도 차이, 반의어와 고급 어휘 확장 참고": "Reference for synonym candidates, intensity, antonyms, and advanced vocabulary",
  "추천 · 우선 참고": "Recommended · Primary Reference",
  "유의어·반의어·고급 어휘와 문맥별 단어 차이를 우선 참고해요.": "Prioritize synonyms, antonyms, advanced vocabulary, and contextual differences.",
  "실전 표현": "Practical Expressions",
  "자연스러운 영어 표현과 실제 사용 맥락을 확인해요.": "Explore natural expressions and authentic usage contexts.",
  "문맥 학습": "Context Learning",
  "영상과 실제 문맥을 활용한 영어 어휘·표현 자료를 살펴봐요.": "Explore vocabulary and expressions through video and real contexts.",
  "영어 교육": "English Education",
  "영어 교육 자료와 어휘·문법 교수 아이디어를 참고해요.": "Refer to English teaching resources and vocabulary and grammar ideas.",
  "학습 자료": "Learning Resources",
  "학습자용 영어 문법과 어휘 콘텐츠를 확인해요.": "Explore English grammar and vocabulary content for learners.",
  "매일 꺼내 보는 영어 표현": "Everyday English Expressions",
  "카드를 누르면 해당 블로그가 새 탭에서 열려요.": "Select a card to open the blog in a new tab.",
  "그동안 어떻게 지냈어요?": "How have you been?",
  "오랜만에 만난 사람과 자연스럽게 대화를 시작하는 표현을 익힙니다.": "Learn an expression for naturally starting a conversation after a long time.",
  "지금 처리하고 있어요.": "I'm working on it.",
  "업무 진행 상황을 짧고 분명하게 전달하는 표현을 다룹니다.": "Learn to communicate work progress briefly and clearly.",
  "큰일 아니에요.": "It's no big deal.",
  "작은 실수나 걱정을 가볍게 받아들이도록 안심시키는 표현입니다.": "Use this expression to reassure someone about a minor mistake or concern.",
  "렛츠링글리쉬어학원": "Let's Ringlish Academy",
  "링크를 누르면 네이버 블로그에서 원문을 확인할 수 있습니다.": "Open the link to view the original post on Naver Blog.",
  "암기함": "Memorization Box",
  "복습": "Review",
  "사용할 때": "When to use it",
  "암기함에 저장": "Save to Memorization Box",
  "추천이 어색해요": "This suggestion feels unnatural",
  "의견 전달됨": "Feedback sent",
  "이해했어요": "Got it",
  "퀴즈 시작": "Start Quiz",
  "다음 표현": "Next Expression",
  "결과 보기": "View Results",
  "가장 알맞은 표현을 선택하세요.": "Choose the most appropriate expression.",
  "오늘의 표현 5개를 완료했어요.": "You completed today's five expressions.",
  "모든 표현을 정확히 구별했어요.": "You distinguished every expression correctly.",
  "틀린 표현은 복습 목록에 자동으로 담았습니다.": "Incorrect expressions were added to your review list.",
  "암기함 보기": "View Memorization Box",
  "복습 확인": "Review Now",
  "일반모드 홈으로": "Back to General Home",
  "저장한 표현은 암기해도 사라지지 않아요.": "Saved expressions remain available after memorization.",
  "복습 목록에 담기": "Add to Review",
  "아직 저장한 표현이 없어요.": "No saved expressions yet.",
  "오늘의 카드에서 다시 보고 싶은 표현을 저장해보세요.": "Save expressions you want to revisit from today's cards.",
  "오늘의 5개 보기": "View Today's Five",
  "복습할 표현": "Expressions to Review",
  "저장했거나 퀴즈에서 틀린 표현을 다시 확인하세요.": "Review saved expressions and expressions missed in the quiz.",
  "퀴즈 오답": "Quiz Mistake",
  "복습 완료": "Review Complete",
  "지금 복습할 표현이 없어요.": "There are no expressions to review now.",
  "표현을 저장하거나 퀴즈 오답이 생기면 이곳에 모입니다.": "Saved and missed expressions appear here.",
  "유의어 어휘": "Synonym Vocabulary",
  "테스트": "Test",
  "유의어 테스트 완료": "Synonym Test Complete",
  "틀린 어휘는 오답 복습에 자동으로 저장했습니다.": "Incorrect vocabulary was saved to Wrong Answer Review.",
  "문제를 모두 정확히 풀었습니다.": "You answered every question correctly.",
  "다시 구별할 어휘": "Vocabulary to Revisit",
  "정답만 외우지 말고 쉬운 표현과 뉘앙스를 함께 확인하세요.": "Review the simpler expression and nuance instead of memorizing only the answer.",
  "복습할 오답이 없습니다.": "There are no wrong answers to review.",
  "문제를 틀리면 해당 어휘가 이곳에 자동으로 모입니다.": "Missed vocabulary appears here automatically.",
  "유의어 어휘 보기": "View Synonym Vocabulary",
  "기사 본문 · 영문 기사 읽기": "Full Article · Read in English",
  "이 문단 해석 보기": "Show Paragraph Translation",
  "기사 원문 본문이 등록되지 않았습니다": "The original article text is not available",
  "원문 가져오기": "Import Original Article",
  "출처에서 원문 확인": "View Original Source",
  "읽기 팁": "Reading Tip",
  "모든 문장을 완벽히 이해하기보다 핵심 동사와 주제를 먼저 잡아보세요.": "Identify the key verbs and topic before trying to understand every sentence.",
  "추천 루틴": "Recommended Routine",
  "기사 읽기 → 필요한 단락 해석 → 표현 확인 → 1분 퀴즈": "Read article → Translate key paragraphs → Review expressions → 1-minute quiz",
  "더 많은 기사 학습하기": "Explore More Articles",
  "검색과 필터로 원하는 기사를 찾아보세요.": "Use search and filters to find an article.",
  "개인 원문 가져오기": "Import Your Own Article",
  "기사 검색": "Search Articles",
  "카테고리 선택": "Select Category",
  "정렬 기준": "Sort By",
  "전체 카테고리": "All Categories",
  "최신순": "Newest",
  "제목순": "Title",
  "카테고리순": "Category",
  "기사 열기": "Open Article",
  "조건에 맞는 기사가 없습니다.": "No articles match these filters.",
  "검색어 또는 카테고리를 다시 조정해 주세요.": "Adjust the search term or category.",
  "이전 기사": "Previous Article",
  "다음 기사": "Next Article",
  "해석 닫기": "Hide Translation",
  "문단 해석": "Translate Paragraph",
  "문장 저장": "Save Sentence",
  "핵심 표현": "Key Expressions",
  "1분 뉴스 이해 퀴즈": "1-Minute News Comprehension Quiz",
  "표현·단락·기사 전체 내용을 4문제로 확인합니다.": "Check expressions, paragraphs, and the full article with four questions.",
  "퀴즈 기준을 통과했어요!": "You passed the quiz!",
  "한 번 더 확인해볼까요?": "Would you like to review once more?",
  "오늘의 기사 학습이 자동 완료되었습니다.": "Today's article lesson was completed automatically.",
  "본문을 끝까지 읽으면 학습이 완료됩니다.": "Finish reading the article to complete the lesson.",
  "3문제 이상 맞히면 학습 완료 기준을 충족합니다.": "Answer at least three questions correctly to meet the completion requirement.",
  "퀴즈 제출하기": "Submit Quiz",
  "현재 보유한 데이터는 기사 제목·요약과 학습용 재구성 문장뿐입니다. 아래 버튼으로 원문 자동 추출을 시도하거나 직접 붙여넣어 학습할 수 있습니다.": "Only the article title, summary, and reconstructed learning sentences are available. Import the original text automatically or paste it directly.",
  "오늘의 기사 완료됨": "Today's Article Completed",
  "읽기 + 퀴즈로 자동 완료": "Complete Automatically after Reading + Quiz",
  "읽기와 퀴즈 기록이 저장되었습니다.": "Your reading and quiz results were saved.",
  "본문을 읽고 퀴즈 3문제 이상 맞히면 완료됩니다.": "Read the article and answer at least three quiz questions correctly to complete it.",
  "제목, 요약, 카테고리 검색": "Search title, summary, or category",
  "학습 문장": "Learning Sentences",
  "기사 읽기 모드": "Article Reading Mode",
  "이 문단의 해석이나 표현을 메모하세요.": "Write notes about the translation or expressions in this paragraph.",
  "뜻은 필요한 문장만 확인해보세요.": "Check meanings only for sentences that need them.",
  "오늘의 뉴스 핵심 문장 듣기": "Play today's key news sentence",
  "기사 주제를 나타내는 대표 이미지": "Featured image representing the article topic",
  "본문을 읽은 뒤 확인하세요": "Review after reading the article",
  "대표 문장과 학습 포인트": "Key Sentence and Learning Points",
  "대표 문장 해석": "Key Sentence Translation",
  "학습 포인트": "Learning Point",
  "말하기 재생 설정": "Speaking Playback Settings",
  "재생 속도": "Playback Speed",
  "현재 영어 문장 듣기": "Play Current English Sentence",
  "문장 듣기": "Play Sentence",
  "장면 이해 완료": "Scene Understood",
  "이 장면 이해했어요": "I Understand This Scene",
  "문장 뜻": "Sentence Meaning",
  "제공된 영어 원문을 의미 단위로 끊어 직접 해석해 보세요.": "Break the original English sentence into meaningful units and interpret it.",
  "클리어 완료": "Clear Complete",
  "다음 문장": "Next Sentence",
  "이전 문장": "Previous Sentence",
  "정답 확인": "Check Answer",
  "다음 문제": "Next Question",
  "대표 문장 듣기": "Play Key Sentence",
  "변형 문장": "Variation Sentence",
  "오늘의 표현을 익혔어요.": "You learned today's expression.",
  "저장 취소": "Remove from Saved",
  "저장됨": "Saved",
  "저장": "Save",
  "첫 페이지로 이동": "Go to First Page",
  "이전 페이지로 이동": "Go to Previous Page",
  "다음 페이지로 이동": "Go to Next Page",
  "마지막 페이지로 이동": "Go to Last Page",
  "다음 영어 단어의 뜻으로 가장 적절한 것은?": "Which meaning best matches the following English word?",
  "다음 한국어 뜻에 해당하는 영어 단어는?": "Which English word matches the following meaning?",
  "3회 반복": "Repeat 3 Times",
  "CSV 업로드": "Upload CSV",
  "시험 모드": "Exam Mode",
  "학습 모드": "Study Mode",
  "오답 다시풀기": "Retry Wrong Answers",
  "라이트모드": "Light Mode",
  "기록 초기화": "Reset Records",
  "초등용 읽기": "Elementary Reading",
  "영어동화": "English Story",
  "영어 동요": "English Songs",
  "오늘도 별을 모아봐요": "Collect more stars today",
  "이름": "Name",
  "초등학교 4학년": "Grade 4",
  "초등 모드에 온 걸 환영해요!": "Welcome to Elementary Mode!",
  "오늘 영어 3개만 해볼까요?": "Shall we complete three English activities today?",
  "짧게 끝내고 별을 모아봐요.": "Finish short activities and collect stars.",
  "이름 저장하고 시작": "Save Name and Start",
  "오늘의 미션 허브": "Today's Mission Hub",
  "오늘 0개 했어요! 3개 남았어요.": "0 completed today! 3 remaining.",
  "오늘 미션": "Today's Mission",
  "단어 카드 5장": "5 Vocabulary Cards",
  "그림 보고 단어 맞히기": "Match Words to Pictures",
  "오늘의 문장 1개": "1 Sentence Today",
  "듣고 따라 말하기": "Listen and Repeat",
  "확인 놀이 3문제": "3 Quick-Check Questions",
  "별 3개 모으기": "Collect 3 Stars",
  "더 하고 싶을 때": "Want to Learn More?",
  "더 해보기": "Try More",
  "짧은 글 읽기": "Read a Short Text",
  "부모님께 영어로 말해보세요": "Tell Your Parent in English",
  "그림 속 단어 5개를 찾아보자!": "Find Five Words in the Pictures!",
  "카드를 열고 듣기 버튼으로 발음을 확인해요.": "Open each card and use the audio button to hear its pronunciation.",
  "그림을 보고 단어를 맞혀보세요.": "Look at the picture and guess the word.",
  "카드 열기": "Open Card",
  "따라 읽기 완료": "Reading Complete",
  "핵심 단어": "Key Vocabulary",
  "소리 내어 읽고 뜻을 확인해 보세요.": "Read aloud and check the meaning.",
  "이렇게도 말해보세요": "Try Saying It This Way",
  "한 줄씩 읽고, 마지막에 딱 1문제만 풀어요.": "Read one line at a time, then answer one question.",
  "미나는 작은 정원이 있어요.": "Mina has a small garden.",
  "미나는 노란 꽃 세 송이를 심어요.": "Mina plants three yellow flowers.",
  "작은 새 한 마리가 정원에 찾아와요.": "A little bird visits the garden.",
  "미나는 새를 보고 기뻐해요.": "Mina is happy to see the bird.",
  "정원": "garden",
  "새": "bird",
  "누가 미나의 정원에 찾아왔나요?": "Who visited Mina's garden?",
  "작은 새": "A little bird",
  "큰 강아지": "A big dog",
  "글에서 답을 찾아보세요.": "Find the answer in the text.",
  "오늘의 추천 1편": "Today's Recommended Story",
  "읽기 전 질문: 길을 잃은 토끼는 누가 도와줄까요?": "Before reading: Who will help the lost rabbit?",
  "작은 별이 하늘에 살아요.": "A little star lives in the sky.",
  "별은 길을 잃은 토끼를 비춰줘요.": "The star shines on the lost rabbit.",
  "토끼는 집으로 가는 길을 찾아요.": "The rabbit finds the way home.",
  "읽고 나서 골라봐요": "Choose After Reading",
  "재미있었어요": "It was fun",
  "따뜻했어요": "It felt warm",
  "또 읽고 싶어요": "I want to read it again",
  "마음에 드는 느낌을 하나 골라요.": "Choose the reaction you like.",
  "오늘의 영어 동요": "Today's English Song",
  "힌트: 반짝반짝 작은 별처럼 손을 반짝이며 따라 불러요.": "Tip: Sing along while twinkling your hands like a little star.",
  "후렴 따라했어요": "I Sang the Chorus",
  "한 번 더 듣기": "Listen Again",
  "딱 3문제 확인 놀이": "Three-Question Quick Check",
  "별 3개를 모아볼까?": "Can you collect three stars?",
  "놀이 1. apple의 뜻은?": "Question 1. What does “apple” mean?",
  "사과": "apple",
  "자동차": "car",
  "놀이 2. I like apples.의 뜻은?": "Question 2. What does “I like apples.” mean?",
  "나는 사과를 좋아해요.": "I like apples.",
  "나는 학교에 가요.": "I go to school.",
  "놀이 3. 미나의 정원에 찾아온 것은?": "Question 3. What visited Mina's garden?",
  "우주선": "A spaceship",
  "틀려도 다시 고르면 돼요!": "Try again if you get one wrong!",
  "나의 영어 별 스티커": "My English Star Stickers",
  "해낸 날들이 쌓이고 있어요": "Your completed days are adding up",
  "매일 한 미션이라도 끝내면 캘린더에 별이 남아요.": "Complete at least one mission each day to earn a calendar star.",
  "아직 기록이 없어요": "No records yet",
  "학습을 완료하면 이 날짜에 별이 생겨요.": "A star appears on this date when you complete a lesson.",
  "아직": "Not yet",
  "읽기": "Reading",
  "동화": "Story",
  "동요": "Song",
  "이번 주 목표 5 / 7": "Weekly Goal 5 / 7",
  "수능 지문 훈련": "CSAT Passage Training",
  "중등 지문 훈련": "Middle School Passage Training",
  "완료 후 다음 지문 계속": "Continue to the Next Passage after Completion",
  "기본 독해": "Foundational Reading",
  "실전 독해": "Exam Reading",
  "취약 유형 집중 훈련": "Focused Weak-Type Training",
  "유형 전략": "Question-Type Strategies",
  "핵심 어휘와 문장 구조": "Key Vocabulary and Sentence Structure",
  "구문 분석": "Syntax Analysis",
  "오늘의 진도와 약점 확인": "Review Today's Progress and Weaknesses",
  "학습 기록": "Study Records",
  "완료한 학습과 남은 항목을 한눈에 확인하세요.": "See completed and remaining activities at a glance.",
  "다음 학습": "Next Lesson",
  "학습 기준": "Learning Sequence",
  "단어 학습, 지문 풀이, 오답 복습을 순서대로 점검합니다.": "Review vocabulary, passage questions, and wrong answers in sequence.",
  "전체 학습 내용 초기화": "Reset All Learning Data",
  "빠른 학습": "Quick Study",
  "진도/기록": "Progress / Records",
  "오늘의 10단어": "Today's 10 Words",
  "먼저 단어의 뜻을 떠올려 보세요.": "Recall the meaning before checking it.",
  "수능 단어 보조 예문": "CSAT Vocabulary Example",
  "네이버에서 더 보기": "View More on Naver",
  "헷갈림": "Unsure",
  "모름": "Don't Know",
  "하루 지문을 한 문제씩 풀고 다음 DAY로 이어갑니다.": "Solve one passage question at a time and continue to the next day.",
  "지문 분석 보기": "View Passage Analysis",
  "주제": "Topic",
  "이 글의 주제로 가장 알맞은 것은?": "Which topic best fits this passage?",
  "매일 조금씩 읽는 습관의 효과": "The benefits of reading a little every day",
  "밤에 일찍 자는 방법": "Ways to go to bed early",
  "긴 이야기를 쓰는 방법": "How to write a long story",
  "새 책을 사는 이유": "Reasons to buy new books",
  "학습에서 적절한 어려움이 장기적 이해를 강화하는 방식": "How appropriate difficulty strengthens long-term understanding",
  "모든 학습 장애물을 제거해야 하는 이유": "Why all learning obstacles should be removed",
  "경쟁적인 학습 환경이 성취를 높이는 과정": "How competitive learning environments improve achievement",
  "쉬운 설명만으로 완전한 숙달에 이르는 방법": "How easy explanations alone lead to complete mastery",
  "이전 문제": "Previous Question",
  "다음 글의 주제로 가장 적절한 것은?": "Which topic best fits the following passage?",
  "취약한 유형부터 훈련하고 정답률 개선을 확인하세요": "Train your weakest question types first and track improvement.",
  "가장 취약 · 먼저 훈련": "Weakest · Train First",
  "이번 주 추천": "Recommended This Week",
  "5문제 시작": "Start 5 Questions",
  "가장 많이 개선": "Most Improved",
  "전체": "All",
  "추천": "Recommended",
  "취약": "Weak",
  "강점": "Strong",
  "유지 필요": "Needs Maintenance",
  "최우선 추천": "Top Priority",
  "현재 정답률": "Current Accuracy",
  "최근 풀이": "Recent Attempts",
  "최근 오답": "Recent Mistakes",
  "유형 상세": "Type Details",
  "5문제 훈련": "Practice 5 Questions",
  "최근 상승": "Recently Improved",
  "안정권": "Stable",
  "오늘 지문으로 익히는 어휘와 구문": "Vocabulary and Syntax from Today's Passage",
  "필수 어휘": "Essential Vocabulary",
  "복습 단어로 저장": "Save as Review Vocabulary",
  "지문 속 핵심 숙어·표현": "Key Phrases and Expressions in the Passage",
  "단어 하나가 아니라 함께 쓰이는 덩어리로 익혀보세요.": "Learn words as useful chunks, not in isolation.",
  "복습 표현으로 저장": "Save as Review Expression",
  "문장 끊어읽기": "Sentence Chunking",
  "주어": "Subject",
  "동사": "Verb",
  "목적격 보어": "Object Complement",
  "수능모드에서 직접 저장한 항목만 표시됩니다.": "Only items saved directly in CSAT Mode are shown.",
  "저장한 단어가 없습니다.": "No saved words.",
  "수능 단어장 또는 오늘의 지문에서 복습할 단어를 저장해보세요.": "Save vocabulary from CSAT Vocabulary or today's passage for review.",
  "저장한 문장이 없습니다.": "No saved sentences.",
  "수능 지문에서 중요 문장 버튼을 누르면 이곳에 모입니다.": "Important sentences saved from CSAT passages appear here.",
  "오늘의 지문으로": "Go to Today's Passage",
  "수능 완료 기록": "CSAT Completion Records",
  "전체 루틴 완료일": "Full-Routine Completion Days",
  "아직 완료된 수능 학습이 없습니다.": "No completed CSAT learning yet.",
  "Day 단어 학습": "Day Vocabulary Study",
  "기록 없음": "No Record",
  "지문": "Passage",
  "수능 지문 완료": "CSAT Passage Complete",
  "유형훈련": "Type Training",
  "유형별 문제 풀이": "Question-Type Practice",
  "오답복습": "Wrong Answer Review",
  "학습 루틴 점검": "Learning Routine Review",
  "압박보다 꾸준한 학습 방향을 확인하는 요약입니다.": "A summary focused on consistent progress rather than pressure.",
  "오늘 진행 전": "Not Started Today",
  "최근 7일": "Last 7 Days",
  "5일 학습": "5 Study Days",
  "평균 정답률": "Average Accuracy",
  "해설 확인": "Explanations Reviewed",
  "복습 대기": "Awaiting Review",
  "오늘 확인": "Today's Check",
  "오늘 지문 풀이": "Today's Passage",
  "대기": "Pending",
  "오답 복습 예약": "Wrong-Answer Review Scheduled",
  "취약 유형 TOP 3": "Top 3 Weak Question Types",
  "이번 주 학습 코멘트": "This Week's Learning Note",
  "빈칸 추론": "Blank Inference",
  "문장 삽입": "Sentence Insertion",
  "순서 배열": "Paragraph Ordering",
  "요지": "Main Point",
  "주제 파악": "Identify the Topic",
  "주장과 근거": "Claim and Evidence",
  "필자가 전달하려는 핵심 메시지를 파악하는 유형": "Identify the writer's central message.",
  "주제문 파악": "Identify the Topic Sentence",
  "반복되는 핵심 개념으로 글의 중심 소재를 찾는 유형": "Find the central subject through repeated key concepts.",
  "대조 구조 파악": "Identify Contrast Structure",
  "전후 문맥과 논리 흐름으로 핵심 의미를 추론하는 유형": "Infer the key meaning from context and logical flow.",
  "지시어 추적": "Track References",
  "지시어와 연결 관계로 문장이 들어갈 위치를 찾는 유형": "Locate a sentence using references and logical connections.",
  "추상어 해석": "Interpret Abstract Language",
  "함축 의미 추론": "Infer Implied Meaning",
  "비유와 문맥 속 표현이 실제로 의미하는 바를 찾는 유형": "Infer the intended meaning of figurative and contextual expressions.",
  "연결사 판단": "Identify Connectors",
  "글의 순서 배열": "Paragraph Ordering",
  "연결사와 정보 흐름으로 문단의 순서를 배열하는 유형": "Order paragraphs using connectors and information flow.",
  "문맥 단서": "Context Clues",
  "어휘 추론": "Vocabulary Inference",
  "문맥에 맞는 어휘 의미와 쓰임을 판단하는 유형": "Determine vocabulary meaning and usage from context.",
  "정보 위치 추적": "Locate Information",
  "장문 독해": "Long-Passage Reading",
  "긴 글의 흐름을 유지하며 여러 문제를 해결하는 유형": "Answer multiple questions while following a long passage.",
  "핵심어 대응": "Match Keywords",
  "요약문 완성": "Complete the Summary",
  "핵심 내용을 압축한 요약문의 빈칸을 완성하는 유형": "Complete blanks in a condensed summary.",
  "수식 관계": "Modification Structure",
  "어법": "Grammar",
  "문장 구조와 문법 관계가 올바른지 판단하는 유형": "Determine whether sentence structure and grammar are correct.",
  "제목 찾기": "Choose the Title",
  "글 전체를 아우르는 핵심 제목을 고르는 유형": "Choose a title that covers the entire passage.",
  "습관": "habit",
  "이해하다": "understand",
  "자신감 있는": "confident",
  "계속하다": "continue",
  "힘이 들지 않는": "effortless",
  "인출하다": "retrieve",
  "재구성하다": "reconstruct",
  "사전 지식": "prior knowledge",
  "좌절감": "frustration",
  "감당할 수 있는": "manageable",
  "매끄럽고 힘이 들지 않는": "smooth and effortless",
  "겉으로 쉽게 느껴지는 학습에 대한 통념을 나타냅니다.": "Describes the common belief that learning should feel easy.",
  "생각을 인출하다": "retrieve ideas",
  "기억 속 정보를 의식적으로 떠올리는 학습 맥락의 표현입니다.": "Used when consciously recalling information from memory.",
  "알고 있는 것을 재구성하다": "reconstruct what one knows",
  "what절 전체가 reconstruct의 목적어입니다.": "The entire what-clause functions as the object of “reconstruct.”",
  "새로운 내용을 이해하기 전에 이미 알고 있는 지식을 뜻합니다.": "Knowledge already held before learning new material.",
  "장악하다, 지배하기 시작하다": "take over; begin to dominate",
  "여기서는 좌절감이 학습 상태를 지배하게 되는 상황을 뜻합니다.": "Here, frustration begins to dominate the learning state.",
  "감당할 수 있는 상태로 남다": "remain manageable",
  "어려움이 지나치지 않고 학습자가 계속 다룰 수 있음을 나타냅니다.": "The difficulty remains within the learner's ability to handle.",
  "공식 공개문항 중심 운영 원칙": "Official-Question Operating Policy",
  "학생과 부모가 모든 문항의 출처와 변형 여부를 즉시 확인할 수 있도록 관리합니다.": "Every question clearly shows its source and whether it was modified.",
  "허용하는 기본 출처": "Approved Primary Sources",
  "한국교육과정평가원 수능·6월·9월 모의평가, 시도교육청 전국연합학력평가, EBS 공식 연계 자료만 기본 학습 목록에 포함합니다.": "The default list includes only official KICE CSAT and mock exams, regional education-office exams, and official EBS materials.",
  "기본 모드 제외 기준": "Default-Mode Exclusion Criteria",
  "출처가 불명확한 사설 문항, 출처를 검증하지 못한 전재 자료, AI 생성 문항은 공식 기출 기본 모드에서 제외합니다.": "Private questions with unclear sources, unverified reproductions, and AI-generated questions are excluded from official mode.",
  "문항별 신뢰 정보": "Question-Level Source Information",
  "출처 기관, 시험명, 시행 시기, 문항 번호, 공식성 등급, 원문 여부와 원출처 기준을 함께 표시합니다.": "Each question displays the institution, exam, date, number, official status, and original-source information.",
  "해설과 변형 표기": "Explanation and Modification Labels",
  "공식 정답과 학습용 자체 해설을 구분하고, 원문 그대로인지 일부 재구성인지 눈에 띄게 표시합니다.": "Official answers are separated from learning explanations, and modified content is clearly labeled.",
  "공식 확인 경로": "Official Verification Links",
  "한국교육과정평가원 수능 홈페이지": "KICE CSAT Website",
  "수능 및 모의평가 공식 공개자료 확인": "View official CSAT and mock-exam materials",
  "EBSi 기출문제": "EBSi Past Questions",
  "수능·모평·학평 기출 및 EBS 자료 확인": "View CSAT, mock-exam, school-exam, and EBS materials",
  "운영 원칙: 원출처 확인이 끝나지 않은 문항은 내용 대신 ‘원문 미등록’ 상태로 표시합니다.": "Policy: Questions awaiting source verification are marked “Original Not Registered” instead of displaying content.",
  "중학교 수준에 맞춘 쉬운 영어 학습 자료": "Accessible English Materials for Middle School",
  "짧은 문장, 기본 어휘, 직관적인 해석을 기준으로 학습 콘텐츠를 구성합니다.": "Content uses short sentences, core vocabulary, and clear translations.",
  "난이도 기준": "Difficulty Standard",
  "중학교 교육과정에서 자주 다루는 기본 어휘와 문장 구조를 중심으로 제공합니다.": "Focuses on core vocabulary and sentence structures common in the middle-school curriculum.",
  "문장 길이": "Sentence Length",
  "한 문장에 담긴 정보를 줄이고 주어와 동사를 쉽게 찾을 수 있도록 구성합니다.": "Sentences contain less information so subjects and verbs are easy to identify.",
  "해석과 설명": "Translation and Explanation",
  "직역보다 문맥을 이해하기 쉬운 자연스러운 해석과 짧은 문법 설명을 제공합니다.": "Provides natural translations and concise grammar explanations.",
  "단어, 지문 읽기, 문제 풀이, 오답 복습을 수능 모드와 동일한 흐름으로 연습합니다.": "Uses the same vocabulary, passage, question, and review flow as CSAT Mode.",
  "중등 모드 자료는 ValueTime이 중학교 수준 학습을 위해 자체 구성한 콘텐츠입니다.": "Middle School Mode contains original ValueTime content designed for middle-school learners.",
  "김나혜": "Kim Na-hye",
  "나혜": "Na-hye",
  "3분": "3 min",
  "4분": "4 min",
  "2분": "2 min",
  "보기": "View",
  "Show meaning 버튼을 누르면 한글 뜻이 보여요.": "Select Show Meaning to reveal the meaning.",
  "나혜가 해낸 날들이 쌓이고 있어요": "Na-hye's completed days are adding up",
  "오늘의 중등 학습": "Today's Middle School Learning",
  "중등 영어 · 단어": "Middle School English · Vocabulary",
  "중등모드": "Middle School Mode",
  "수능모드": "CSAT Mode",
  "수능 기초": "CSAT Foundation",
  "수능 핵심": "CSAT Core",
  "고난도": "Advanced",
  "EXAMPLE · 수능 단어 보조 예문": "EXAMPLE · CSAT Vocabulary Example",
  "EXAMPLE · 수능 단어장 보조 예문": "EXAMPLE · CSAT Vocabulary Example",
  "난이도 상 · 예상 8분": "Difficulty High · About 8 min",
  "난이도 중등 · 예상 4분": "Difficulty Middle School · About 4 min",
  "짧은 예문과 함께 익히는 중등 필수 표현입니다.": "Essential middle-school expressions learned through short examples.",
  "수능 완료 기록": "CSAT Completion Records",
  "긴 글의 흐름을 유지하며 여러 문제를 해결하는 유형": "Answer multiple questions while following the flow of a long passage.",
  "최근 7일 중 5일 학습해 루틴이 잘 유지되고 있습니다. 빈칸 추론은 정답 근거 문장을 먼저 찾는 연습을 권장합니다.": "You studied on five of the last seven days and maintained a steady routine. For blank inference, practice locating the evidence sentence first.",
  "지": "P",
  "유": "T",
  "복": "R",
  "페이지": "Page",
  "개 단어장": "words",
  "버튼을 누르면 한글 뜻이 보여요.": "Select the button to reveal the meaning.",
  "학습": "Study",
  "영어 · 단어장": "English · Vocabulary",
  "모드": "Mode",
  "수능 단어장 보조 예문": "CSAT Vocabulary Example",
  "완료 기록": "Completion Records",
  "여러 문제를 해결하는 유형": "Answer multiple questions",
  "긴 글의 흐름을 유지하며 여러 Questions을 해결하는 유형": "Answer multiple questions while following the flow of a long passage.",
  "강도를 높이는 형용사": "Intensifying Adjectives",
  "유의어 선택": "Choose a Synonym",
  "“very big”와 의미가 가장 가까운 고급 어휘는?": "Which advanced word is closest in meaning to “very big”?",
  "big보다 훨씬 큰 크기나 양을 강조한다.": "Emphasizes a much greater size or amount than “big.”",
  "빈칸에 들어갈 가장 적절한 어휘는?": "Which word best completes the blank?",
  "운영팀은 예산 제안서를 늦어도 다음 월요일까지 제출할 예정입니다.": "The operations team will submit the budget proposal no later than next Monday.",
  "아쉽습니다. 표현 포인트를 확인하고 다른 답을 선택해 보세요.": "Not quite. Review the expression point and choose another answer.",
  "새로 문을 연 도서관은 청소년들에게 읽고 공부하고 만날 수 있는 조용하고 편안한 공간을 제공합니다.": "The newly opened library gives teenagers a quiet, welcoming place to read, study, and meet.",
  "건물에는 밝은 열람실과 공용 학습 테이블, 작은 미디어실이 있습니다.": "The building includes bright reading rooms, shared study tables, and a small media room.",
  "프로그램은 지역 가족들의 학습을 더 쉽고 즐겁게 만들도록 설계되었습니다.": "The program is designed to make learning easier and more enjoyable for local families.",
  "편안한 좌석과 큰 창문은 집중력과 창의성을 높이는 차분한 분위기를 만듭니다.": "Comfortable seating and large windows create a calm atmosphere that supports focus and creativity.",
  "도서관은 방과 후 지도와 주말 워크숍을 제공하며 청소년들은 다양한 프로젝트에 참여할 수 있습니다.": "The library offers after-school tutoring and weekend workshops where teenagers can join various projects.",
  "도서관은 지역 기부금과 시 교육 기금의 지원으로 건립되었습니다.": "The library was built with local donations and city education funding.",
  "많은 자원봉사자가 개관 행사를 준비했습니다.": "Many volunteers prepared the opening event.",
  "학부모들은 자녀가 성장하고 관심사를 탐구할 안전한 공간이 생겨 기쁘다고 말했습니다.": "Parents welcomed the safe space where their children can grow and explore their interests.",
  "도서관은 평일 오전 9시부터 오후 8시까지, 주말 오전 10시부터 오후 5시까지 운영됩니다.": "The library is open from 9 a.m. to 8 p.m. on weekdays and from 10 a.m. to 5 p.m. on weekends.",
  "메시지 확인 중": "Checking the Message",
  "공 지문에서 Room 204의 프린터를 사용하라고 안내합니다.": "The notice instructs readers to use the printer in Room 204.",
  "오늘 푼 항목을 기준으로 복습 필요 여부를 확인합니다.": "Review needs are determined from today's completed items.",
  "아직 오늘 문제를 풀지 않았어요": "You have not answered today's questions yet",
  "학습 완료 처리": "Mark Study Complete",
  "헷갈린 문제 저장": "Save as Unsure",
  "약점 유형 복습": "Review Weak Types",
  "관련 예문": "Related Examples",
  "도메인 노트": "Domain Note",
  "업무 영역에서는 용어의 기능, 공정 맥락, 보고서 표현을 함께 익히는 것이 중요합니다.": "In business contexts, learn the term's function, process context, and reporting usage together.",
  "생산 영역에서는 용어의 기능, 공정 맥락, 보고서 표현을 함께 익히는 것이 중요합니다.": "In production contexts, learn the term's function, process context, and reporting usage together.",
  "아직 저장된 오답이 없습니다.": "There are no saved wrong answers yet.",
  "오답입니다. 해설을 확인하세요.": "Incorrect. Review the explanation.",
  "한글 핵심 해설": "Key Explanation",
  "was adjusted는 ‘조정되었다’라는 올바른 수동태입니다.": "“Was adjusted” is the correct passive form meaning that something was changed.",
  "한글 상세 해설": "Detailed Explanation",
  "생산 라인이 결함을 줄이기 위해 조정된 상황이므로 be동사 was 뒤에 과거분사 adjusted가 와야 합니다. 행위자보다 조정된 대상과 결과가 중요한 생산 보고 문장입니다.": "Because the production line was changed to reduce defects, the past participle “adjusted” must follow “was.” The report emphasizes the affected object and result.",
  "선택지별 오답 분석": "Choice-by-Choice Analysis",
  "adjustment는 명사이므로 was 뒤에서 동사 역할을 할 수 없습니다.": "“Adjustment” is a noun and cannot function as the verb after “was.”",
  "adjustedly는 자연스러운 영어 부사 형태가 아닙니다.": "“Adjustedly” is not a natural English adverb.",
  "was 뒤에는 동사원형 adjust가 아니라 과거분사 adjusted가 필요합니다.": "“Was” requires the past participle “adjusted,” not the base verb “adjust.”",
  "영어 예문": "English Examples",
  "에너지가 거의 남지 않은 강한 피로예요.": "Describes extreme tiredness with almost no energy left.",
  "가벼운 피곤함에는 tired가 더 자연스러워요.": "For mild fatigue, “tired” is more natural.",
  "밤샘 비행 후 완전히 지쳤어요.": "I was exhausted after the overnight flight.",
  "매우 배고픈 상태를 구어적으로 강조해요.": "Informally emphasizes being very hungry.",
  "실제로 굶주리는 상황 외에도 일상에서 과장해 말할 수 있어요.": "It can be used as everyday exaggeration, not only for actual starvation.",
  "너무 배고파요. 뭔가 먹으러 가요.": "I'm starving. Let's get something to eat.",
  "보관한 표현으로 시험지 만들기": "Create a Test from Saved Expressions",
  "저장한 항목을 바탕으로 바로 풀 수 있는 4지선다 문제를 만듭니다.": "Create multiple-choice questions from your saved items.",
  "출제 범위": "Test Scope",
  "저장한 단어만": "Saved Words Only",
  "저장한 문장만": "Saved Sentences Only",
  "문제 수": "Number of Questions",
  "난이도": "Difficulty",
  "쉬움": "Easy",
  "보통": "Medium",
  "도전": "Challenge",
  "1차 버전은 모든 문제를 객관식 4지선다로 생성합니다. 저장 항목이 부족하면 보충 문제가 포함됩니다.": "All questions are currently four-choice multiple choice. Supplemental questions are added when there are not enough saved items.",
  "나의 저장 항목 테스트": "My Saved-Item Test",
  "5문제 · 보통": "5 Questions · Medium",
  "단어 뜻": "Word Meaning",
  "보충 문제": "Supplemental Question",
  "‘abandon’의 뜻으로 가장 알맞은 것을 고르세요.": "Choose the best meaning of “abandon.”",
  "정확하다, 정확하다": "accurate; exact",
  "분석하다": "analyze",
  "유지하다": "maintain",
  "포기하다": "abandon; give up",
  "‘accurate’의 뜻으로 가장 알맞은 것을 고르세요.": "Choose the best meaning of “accurate.”",
  "도달하다, 획득하다": "reach; attain",
  "변화": "change",
  "효율적으로": "efficiently",
  "‘achieve’의 뜻으로 가장 알맞은 것을 고르세요.": "Choose the best meaning of “achieve.”",
  "획득하다; 배우다": "acquire; learn",
  "가능성": "possibility",
  "‘access’의 뜻으로 가장 알맞은 것을 고르세요.": "Choose the best meaning of “access.”",
  "동행하다, 동행하다; 반주": "accompany; provide musical accompaniment",
  "채널; 기회, 참가할 권리; 접근하다": "channel; opportunity; right to participate; access",
  "충분하다, 적절하다": "adequate; appropriate",
  "‘accompany’의 뜻으로 가장 알맞은 것을 고르세요.": "Choose the best meaning of “accompany.”",
  "적응하다; 적응하다": "adapt; adjust",
  "명확한": "clear",
  "답안 제출하기": "Submit Answers",
  "짧은 글도 끝까지 읽었어! 아주 좋아.": "You finished the whole short text! Great job.",
  "처음부터 다시 하기": "Start Again",
  "동화 다시 읽기": "Read the Story Again",
  "오늘 동화 한 편 끝! 영어 이야기도 읽을 수 있어.": "You finished today's story! You can read English stories.",
  "별 2개를 모았어요!": "You collected 2 stars!",
  "이날 완료한 미션을 다시 확인해보세요.": "Review the missions completed on this day.",
  "풀이 이력이 쌓이면 개인 기록으로 자동 전환됩니다.": "This switches to your personal history as attempts accumulate.",
  "현재": "Current",
  "자주 틀리는 포인트": "Common Mistake",
  "소재와 필자의 메시지를 혼동하는 실수": "Confusing the subject matter with the writer's message",
  "이번 훈련 전략": "Training Strategy",
  "결론 문장과 근거의 연결을 한 번 더 점검하세요.": "Recheck the connection between the conclusion and its evidence.",
  "이 세부 기술을 우선 확인합니다.": "Focus on this subskill first.",
  "오답 다시 풀기": "Retry Wrong Answers",
  "5문제 빠르게": "Quick 5 Questions",
  "빈칸 주변 문장만 읽고 전체 논리를 놓치는 실수": "Reading only around the blank and missing the overall logic",
  "가장 낮은 정답률이지만 최근 8%p 개선됐어요.": "This is the lowest-accuracy type, but it recently improved by 8 percentage points.",
  "오늘 정답률 0%": "Today's Accuracy 0%",
  "Daily Test 정답률 0%": "Daily Test Accuracy 0%",
  "빈칸에 들어갈 가장 적절한 것은?": "Which option best completes the blank?",
  "풀이 완료": "Completed",
  "by Friday는 ‘금요일까지, 늦어도 금요일에는’이라는 마감 기한을 나타냅니다.": "“By Friday” indicates a deadline: no later than Friday.",
  "on Friday는 금요일 당일에 일어난다는 뜻일 뿐 마감 기한을 나타내지 않습니다.": "“On Friday” means an event occurs that day; it does not express a deadline.",
  "from Friday는 금요일부터 시작한다는 뜻입니다.": "“From Friday” means starting on Friday.",
  "during Friday는 이런 마감 문맥에서 자연스럽지 않습니다.": "“During Friday” is unnatural in this deadline context.",
  "Business 영역에서는 용어의 기능, 공정 맥락, 보고서 표현을 함께 익히는 것이 중요합니다.": "In business contexts, learn the term's function, process context, and reporting usage together.",
  "긴 글의 흐름을 유지하며 여러 문항을 해결하는 유형": "Answer multiple questions while following the flow of a long passage.",
  "학습자 선택": "Select Learner",
  "선택한 학습자 기준으로 진도와 기록이 저장됩니다.": "Progress and records are saved for the selected learner.",
  "최근 학습자": "Recent Learner",
  "저장한 학습 항목을 복습합니다.": "Review saved learning items.",
  "오답과 저장한 어휘·문장을 함께 복습합니다.": "Review wrong answers together with saved vocabulary and sentences.",
  "오늘 복습할 항목을 모두 마쳤습니다.": "You completed all reviews for today.",
  "새 오답이나 저장 항목이 생기면 알맞은 시점에 다시 출제합니다.": "New wrong answers and saved items will return at the right review time.",
  "오늘의 장면과 메시지를 모두 이해했어요.": "You understood today's scene and message.",
  "미드 대사 3개": "3 TV Dialogue Lines",
  "오늘의 TED 메시지 학습이 완료되었습니다.": "Today's TED message lesson is complete.",
  "오늘은 이 메시지를 이해했어요": "I understood today's message",
  "선택한 발언이 이 메시지를 어떻게 뒷받침하는지 앞뒤 스크립트와 함께 기억해 보세요.": "Remember how the selected line supports this message by reviewing the surrounding transcript.",
  "최근 점수": "Latest Score",
  "해설:": "Explanation:",
  "공지문에서 Room 204의 프린터를 사용하라고 안내합니다.": "The notice instructs readers to use the printer in Room 204.",
  "한글": "Korean",
  "짧게 하나만 더 끝내면 오늘 학습 흐름이 이어집니다.": "Complete one more short activity to keep today's momentum going.",
  "오늘 흐름이 좋습니다. 남은 항목은 복습 중심으로 가볍게 마무리하세요.": "You're making good progress. Finish the remaining items with a light review.",
  "학습하기": "Study",
  "지문 풀기": "Solve passage",
  "유형 훈련하기": "Practice question types",
  "어휘·구문 보기": "View vocabulary and syntax",
  "학습 현황 보기": "View learning progress",
  "뉴스 읽기": "Read news",
  "오늘의 TED 시작": "Start today's TED",
  "시험 시작": "Start test",
  "문제 풀기": "Solve questions",
  "시작하기": "Start",
  "이어서 학습": "Continue",
  "복습하기": "Review",
  "학습하러 가기": "Start learning",
  "단어 학습하기": "Study vocabulary",
  "문장으로": "Daily Sentence",
  "단어장으로": "Vocabulary",
  "뜻 보기": "Show meaning",
  "뜻 숨기기": "Hide meaning",
  "해석 보기": "Show translation",
  "해석 접기": "Hide translation",
  "예문 듣기": "Play example",
  "발음 듣기": "Play pronunciation",
  "이전 단어": "Previous word",
  "다음 단어": "Next word",
  "이전 날": "Previous day",
  "다음 날": "Next day",
  "관련 표현": "Related expressions",
  "유의어 어휘": "Synonym Vocabulary",
  "테스트": "Test",
  "오답 복습": "Wrong Answer Review",
  "하루 3~4개씩 정확하게": "Learn 3–4 Words a Day",
  "100개를 한꺼번에 외우지 않고 30일 동안 뜻·예문·뉘앙스를 나눠 학습합니다.": "Learn 100 words over 30 days through meanings, examples, and nuance.",
  "AI 분석": "AI Analysis",
  "뉘앙스 차이": "Nuance",
  "학습 완료": "Mark complete",
  "학습 완료됨": "Completed",
  "정답 확인": "Check answer",
  "정답 제출": "Submit answer",
  "다시 풀기": "Try again",
  "다음 문제": "Next question",
  "오늘은 완료": "Finish for today",
  "오답 노트": "Wrong Answers",
  "정답": "Correct answer",
  "정답입니다.": "Correct.",
  "오답입니다.": "Incorrect.",
  "저장": "Save",
  "저장됨": "Saved",
  "저장 해제": "Remove",
  "닫기": "Close",
  "이전": "Previous",
  "다음": "Next",
  "메인으로 돌아가기": "Back to home",
  "오늘의 학습으로 돌아가기": "Back to today's learning",
  "수능 홈": "CSAT Home",
  "공식 기출 목록으로": "Official questions",
  "원출처에서 확인": "View original source",
  "학습 모드": "Study Mode",
  "실전 모드": "Exam Mode",
  "해설까지 확인했어요": "You reviewed the explanation",
  "오늘 지문 완료": "Complete today's passage",
  "취약 유형 훈련": "Weakness training",
  "오늘의 학습으로": "Back to today's learning",
  "전체 강연 보기": "Watch full talk",
  "메시지 이해하기": "Understand the message",
  "문장 듣기": "Play sentence",
  "수능 리뷰 코치": "CSAT Review Coach",
  "수능 학습 복습": "CSAT Review",
  "기억 점수": "Memory score",
  "개 남음": "remaining",
  "환경설정": "Settings",
  "알림 설정": "Notification Settings",
  "학습 리마인더와 진도 알림을 관리합니다.": "Manage study reminders and progress notifications.",
  "매일 학습 알림": "Daily study reminder",
  "정해진 시간에 오늘의 학습을 알려드립니다.": "Get a reminder for today's learning at your chosen time.",
  "알림 시간": "Reminder time",
  "매일 학습 알림을 받을 시간": "Time to receive the daily reminder",
  "복습 알림": "Review reminders",
  "오답과 저장한 항목의 복습 시점을 알려드립니다.": "Get reminders for wrong answers and saved items.",
  "연속 학습 알림": "Study streak reminders",
  "연속 학습 기록이 끊기기 전에 알려드립니다.": "Get notified before your study streak ends.",
  "주간 리포트": "Weekly report",
  "매주 학습량과 성취도를 요약해서 알려드립니다.": "Receive a weekly summary of progress and achievement.",
  "학습 화면 설정": "Study Display Settings",
  "학습 중 영어 콘텐츠가 표시되는 방식을 선택합니다.": "Choose how learning content is displayed.",
  "표시 모드": "Interface language",
  "영어와 한국어를 함께 볼지 선택하세요.": "Choose the language used across the service.",
  "영어만": "English",
  "전체 영어": "English",
  "영어 + 한국어": "Korean + English",
  "추가 표시 옵션": "Additional display options",
  "예문 해석 자동 표시": "Show example translations",
  "예문 아래에 한국어 해석을 바로 표시합니다.": "Show Korean translations below examples.",
  "품사 표시": "Show parts of speech",
  "단어 카드에 품사를 표시합니다.": "Show parts of speech on vocabulary cards.",
  "발음 기호 표시": "Show pronunciation symbols",
  "Silent / Speaking 모드 표시": "Show Silent / Speaking modes",
  "상단의 Silent / Speaking 전환 버튼을 표시합니다.": "Show the Silent / Speaking switch in the top bar.",
  "단어와 함께 발음 기호를 표시합니다.": "Show pronunciation symbols with vocabulary.",
  "좌측 메뉴 설정": "Sidebar Menu Settings",
  "현재 필요한 학습 메뉴만 좌측 사이드바에 표시합니다. 숨겨도 학습 데이터와 기록은 유지됩니다.": "Choose which learning menus appear in the sidebar. Hidden menus keep all learning data and progress.",
  "일반모드 메뉴 표시": "General mode menus",
  "표현을 더 자연스럽고 정확하게 바꾸는 학습": "Practice more natural and precise expressions",
  "30일 유의어 어휘와 테스트": "30-day synonym vocabulary and tests",
  "오늘의 단어와 예문 학습": "Study today's vocabulary and examples",
  "오늘 바로 쓰는 표현 패턴 학습": "Practice useful daily expression patterns",
  "뉴스 기사 읽기와 표현 학습": "Read news and learn useful expressions",
  "강연 맥락과 메시지 이해": "Understand the context and message of a talk",
  "오늘 학습한 내용 점검": "Check today's learning",
  "토익 문제 풀이": "Practice TOEIC questions",
  "저장한 단어와 문장 복습": "Review saved words and sentences",
  "날짜별 학습 기록 확인": "View daily learning records",
  "저장한 블로그 콘텐츠 학습": "Study saved blog content",
  "설정이 저장되었습니다.": "Settings saved.",
}));

const DYNAMIC_TRANSLATIONS = [
  [/^(\d+)\s*\/\s*(\d+)\s*완료$/, "$1 / $2 completed"],
  [/^(\d+)%\s*완료$/, "$1% complete"],
  [/^오늘 단어\s*(\d+)개$/, "$1 words today"],
  [/^저장 단어\s*(\d+)개 복습 가능$/, "$1 saved words ready for review"],
  [/^복습할 오답\s*(\d+)개 있음$/, "$1 wrong answers to review"],
  [/^오늘 추천 문제\s*(\d+)개$/, "$1 recommended questions today"],
  [/^오답\/북마크\s*(\d+)개 복습 필요$/, "$1 wrong answers/bookmarks to review"],
  [/^매일 토익 풀기 오답\/북마크\s*(\d+)개$/, "Daily TOEIC · $1 wrong answers/bookmarks"],
  [/^저장 단어\s*(\d+)개$/, "$1 saved words"],
  [/^오늘 완료됨$/, "Completed today"],
  [/^최근 결과\s*(.+)$/, "Latest result · $1"],
  [/^최근 학습\s*·?\s*(.+)$/, "Last studied · $1"],
  [/^(\d+)월\s+1일[–-]오늘\s*·\s*저장 단어 우선\s*·\s*(\d+)문제$/, "From $1/1 to today · Saved words first · $2 questions"],
  [/^수능·고등 영어 독해를 위한\s*(\d+)번째 핵심 어휘입니다\.$/, "Core vocabulary #$1 for CSAT and advanced reading."],
  [/^(\d+)\s*\/\s*(\d+)\s*페이지$/, "Page $1 of $2"],
  [/^(\d+)\s*개를 모았어요$/, "$1 words saved"],
  [/^문제\s*(\d+)\s*\/\s*(\d+)$/, "Question $1 of $2"],
  [/^(\d{4}-\d{2}-\d{2})\s*등록\s*·\s*전체 문장 완료까지 고정$/, "Added $1 · Fixed until all sentences are complete"],
  [/^(\d+)개 발화$/, "$1 transcript lines"],
  [/^(.+)\s*·\s*약\s*(\d+)분\s*·\s*중급\s*·\s*영상과 스크립트를 함께 살펴보세요\.$/, "$1 · About $2 min · Intermediate · Explore the video and transcript together."],
  [/^원문 구간\s*(\d{2}:\d{2})$/, "Source timestamp $1"],
  [/^(\d+)\s*\/\s*(\d+)\s*·\s*원문\s*(\d+)번$/, "$1 / $2 · Source line $3"],
  [/^오늘\s*(\d+)번\s*·\s*원문\s*(\d+)번\s*·\s*(\d{2}:\d{2})$/, "Today $1 · Source line $2 · $3"],
  [/^전체 풀이\s*(\d+)\/(\d+)$/, "Total solved $1/$2"],
  [/^(\d{4})년\s*(\d+)월$/, "$1 / $2"],
  [/^(\d+)개 완료$/, "$1 completed"],
  [/^(\d+)월\s*(\d+)일에 완료한 학습$/, "Learning completed on $1/$2"],
  [/^(\d+)개 단위 완료$/, "$1 units completed"],
  [/^(.+)의 영어 탐험!$/, "$1's English Adventure!"],
  [/^(.+)야,\s*오늘 영어 3개만 해볼까요\?$/, "$1, shall we complete three English activities today?"],
  [/^(.+)님,\s*오늘 영어 3개만 해볼까요\?$/, "$1, shall we complete three English activities today?"],
  [/^오늘 미션\s*(\d+)\s*·\s*(\d+)분$/, "Today's Mission $1 · $2 min"],
  [/^더 해보기\s*·\s*(.+)$/, "Try More · $1"],
  [/^(\d+)페이지\s*·\s*(\d+)개 단어$/, "Page $1 · $2 words"],
  [/^(\d+)번 카드$/, "Card $1"],
  [/^(\d+)\s*\/\s*(\d+)\s*페이지\s*·\s*총\s*(\d+)단어$/, "Page $1 of $2 · $3 words total"],
  [/^매일 1문장\s*·\s*(\d+)번$/, "Daily Sentence · No. $1"],
  [/^(\d+)\s*\/\s*(\d+)\s*문장\s*·\s*총\s*(\d+)개$/, "Sentence $1 of $2 · $3 total"],
  [/^(\d+)문장 읽기$/, "Read $1 Sentences"],
  [/^핵심 단어\s*(\d+)개$/, "$1 Key Words"],
  [/^(\d+)\s*\/\s*(\d+)\s*완료\s*·\s*틀려도 다시 고르면 돼요!$/, "$1 / $2 complete · Try again if you get one wrong!"],
  [/^부모 미션\s*(\d+)개 기록$/, "$1 Parent Missions Recorded"],
  [/^(\d+)일 연속\s*(.+)\s*루틴$/, "$1-Day $2 Streak"],
  [/^오늘의\s*(.+)\s*지문$/, "Today's $1 Passage"],
  [/^(.+)\s*공용$/, "$1 Shared"],
  [/^(.+)\s*모드 학습자$/, "$1 Mode Learner"],
  [/^(\d+)\s*\/\s*(\d+)\s*문제\s*·\s*전체\s*(\d+)remaining$/, "Question $1 of $2 · $3 remaining"],
  [/^난이도\s*(.+)\s*·\s*예상\s*(\d+)분$/, "Difficulty $1 · About $2 min"],
  [/^(\d+)문제$/, "$1 questions"],
  [/^(\d+)개$/, "$1 items"],
  [/^(\d+)월\s*(\d+)일\s*학습$/, "Study on $1/$2"],
  [/^(.+)\s*영어\s*·\s*단어장$/, "$1 English · Vocabulary"],
  [/^(.+)모드$/, "$1 Mode"],
  [/^(\d+)\s*\/\s*(\d+)\s*문제\s*·\s*전체\s*(\d+)개 남음$/, "Question $1 of $2 · $3 remaining"],
  [/^복습 대기\s*(\d+)개 있음$/, "$1 reviews pending"],
  [/^이전\s*(\d+)%에서 현재\s*(\d+)%로 향상됐어요\.$/, "Improved from $1% to $2%."],
  [/^(\d+)회$/, "Attempt $1"],
  [/^오답 노트\s*(\d+)$/, "Wrong Answers $1"],
  [/^오답 복습\s*(\d+)$/, "Wrong Answer Review $1"],
  [/^일반 모드\s*·\s*(.+)$/, "General Mode · $1"],
  [/^수능 모드\s*·\s*(.+)$/, "CSAT Mode · $1"],
  [/^(\d+)개 남음\s*·\s*전체\s*(\d+)개$/, "$1 remaining · $2 total"],
  [/^DAY\s+(\d+)\s*·\s*WORD\s+(\d+)\s*·\s*형용사$/, "DAY $1 · WORD $2 · ADJECTIVE"],
  [/^DAY\s+(\d+)\s*·\s*WORD\s+(\d+)\s*·\s*동사$/, "DAY $1 · WORD $2 · VERB"],
  [/^DAY\s+(\d+)\s*·\s*WORD\s+(\d+)\s*·\s*상태$/, "DAY $1 · WORD $2 · STATE"],
];

function translateValue(value) {
  const trimmed = String(value || "").trim();
  if (!trimmed) return value;
  if (UI_TRANSLATIONS.has(trimmed)) return String(value).replace(trimmed, UI_TRANSLATIONS.get(trimmed));
  let translated = String(value);
  for (const [pattern, replacement] of DYNAMIC_TRANSLATIONS) {
    if (!pattern.test(trimmed)) continue;
    translated = String(value).replace(trimmed, trimmed.replace(pattern, replacement));
    break;
  }
  [...UI_TRANSLATIONS.entries()]
    .filter(([source]) => source.length >= 2)
    .sort(([left], [right]) => right.length - left.length)
    .forEach(([source, target]) => {
      if (translated.includes(source)) translated = translated.replaceAll(source, target);
    });
  return translated
    .replaceAll("오전", "AM")
    .replaceAll("오후", "PM");
}

function translateElementAttributes(element, english) {
  ["aria-label", "title", "placeholder"].forEach(attribute => {
    if (!element.hasAttribute(attribute)) return;
    const originalAttribute = `data-ui-original-${attribute.replace("aria-", "aria")}`;
    if (english) {
      if (!element.hasAttribute(originalAttribute)) element.setAttribute(originalAttribute, element.getAttribute(attribute));
      const translated = translateValue(element.getAttribute(originalAttribute));
      if (element.getAttribute(attribute) !== translated) element.setAttribute(attribute, translated);
    } else if (element.hasAttribute(originalAttribute)) {
      element.setAttribute(attribute, element.getAttribute(originalAttribute));
      element.removeAttribute(originalAttribute);
    }
  });
}

export function applyUiLanguage(root = document, mode = document.documentElement.dataset.studyDisplay) {
  const english = mode === "english_only";
  const elementRoot = root.nodeType === Node.ELEMENT_NODE ? root : root.documentElement;
  if (!elementRoot) return;
  [elementRoot, ...elementRoot.querySelectorAll("*")].forEach(element => translateElementAttributes(element, english));
  const walker = document.createTreeWalker(elementRoot, NodeFilter.SHOW_TEXT);
  const textNodes = [];
  while (walker.nextNode()) textNodes.push(walker.currentNode);
  textNodes.forEach(node => {
    if (["SCRIPT", "STYLE"].includes(node.parentElement?.tagName)) return;
    if (english) {
      if (node.__valueTimeOriginalText === undefined) node.__valueTimeOriginalText = node.nodeValue;
      const translated = translateValue(node.__valueTimeOriginalText);
      if (node.nodeValue !== translated) node.nodeValue = translated;
    } else if (node.__valueTimeOriginalText !== undefined) {
      if (node.nodeValue !== node.__valueTimeOriginalText) node.nodeValue = node.__valueTimeOriginalText;
      delete node.__valueTimeOriginalText;
    }
  });
}

export function observeUiLanguage(root) {
  const observer = new MutationObserver(records => {
    records.forEach(record => {
      record.addedNodes.forEach(node => {
        if (node.nodeType === Node.ELEMENT_NODE) applyUiLanguage(node);
        else if (node.nodeType === Node.TEXT_NODE && node.parentElement) applyUiLanguage(node.parentElement);
      });
    });
  });
  observer.observe(root, { childList: true, subtree: true });
  applyUiLanguage(root);
  return () => observer.disconnect();
}
